# Site settings
title: Rianne Schoenmacker
email: info@rianneschoenmacker.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the portfolio of Rianne Schoenmacker, where textiles and technology converge to create innovative, 
  interactive art. My work focuses on pushing the boundaries of traditional textile design. Each project explores
  the relationship between touch, light, and texture, creating immersive, dynamic experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rianneschoenmacker.com" # the base hostname & protocol for your site
github_username:  rianneschoenmacker
instagram_username:  rianne.schoenmacker

# Build settings
markdown: kramdown
permalink: pretty
